### ISSUE TITLE
[Karma] Don't ping on karma notification

### ISSUE THREAD

**Issue by YoannMa** [Dwakof/ebot#187]

**Comment by xiprox** [comment]
As a part of this, we may want to consider specifying who caused the change. For example, something like the following could work: "Ecto smacked xip. -5 karma." or "Ecto awarded xip. +5 karma."

Alternatively, we could consider not posting update messages at all.

**Comment by YoannMa** [comment]
That could be fun indeed, if we got with that, we need to store the user info in the database, requiring a reset of the current info.
